package NewPack;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.*;
import java.sql.*;


/*
 * crop_image.java
 *

 */

public class crop_image extends javax.swing.JFrame {

    /** Creates new form crop_image */
    public crop_image() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 120, 120, 120));
        setMinimumSize(new java.awt.Dimension(710, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Hair");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(141, 36, 27, 17);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(555, 32, 90, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(218, 35, 319, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("ForeHead");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(141, 96, 59, 17);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(555, 92, 90, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(218, 95, 319, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Nose");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(147, 212, 29, 17);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(555, 208, 90, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(218, 211, 319, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Eye");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(147, 152, 22, 17);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(555, 148, 90, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(218, 151, 319, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Chin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(147, 334, 30, 17);

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setText("Browse");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(555, 330, 90, 25);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(218, 333, 319, 20);

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.setText("Upload");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(270, 440, 90, 25);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("Mouth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(147, 274, 40, 17);

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("Browse");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(555, 270, 90, 25);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(218, 273, 319, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 440, 90, 25);

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton12.setText("Browse");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(560, 380, 90, 25);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 380, 319, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("Full Image");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 380, 70, 17);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 0, 73, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPack/resources/Cropimage.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 0, 740, 490);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField1.setText(file.toString());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField2.setText(file.toString());
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField4.setText(file.toString());
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField3.setText(file.toString());
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField6.setText(file.toString());
       }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField5.setText(file.toString());
       }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           jTextField1.setText("");
           jTextField2.setText("");
           jTextField3.setText("");
           jTextField4.setText("");
           jTextField5.setText("");
           jTextField6.setText("");
           jTextField7.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        try {   
                 String ha = jTextField1.getText();
                 File file = new File(ha);
                 FileInputStream  fis = new FileInputStream(file);
                 
                 String frh = jTextField2.getText();
                 File file1 = new File(frh);
                 FileInputStream  fis1 = new FileInputStream(file1);
                 
                 String ey = jTextField4.getText();
                 File file2 = new File(ey);
                 FileInputStream  fis2 = new FileInputStream(file2);
                 
                 String nos = jTextField3.getText();
                 File file3 = new File(nos);
                 FileInputStream  fis3 = new FileInputStream(file3);
                 
                 String mou = jTextField6.getText();
                 File file4 = new File(mou);
                 FileInputStream  fis4 = new FileInputStream(file4);
                 
                 String chn = jTextField5.getText();
                 File file5 = new File(chn);
                 FileInputStream  fis5 = new FileInputStream(file5); 
                 
                 String full = jTextField7.getText();
                 File file6 = new File(full);
                 FileInputStream  fis6 = new FileInputStream(file6); 
                 
            
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
                     PreparedStatement pstmt = conn.prepareStatement("insert into crop (hair,forehd,eye,nose,mouth,chin,h,f,e,n,m,c,fullimage)values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                      
                    pstmt.setBinaryStream(1, (InputStream)fis, (int)(file.length())); 
                    pstmt.setBinaryStream(2, (InputStream)fis1, (int)(file1.length())); 
                    pstmt.setBinaryStream(3, (InputStream)fis2, (int)(file2.length())); 
                    pstmt.setBinaryStream(4, (InputStream)fis3, (int)(file3.length())); 
                    pstmt.setBinaryStream(5, (InputStream)fis4, (int)(file4.length())); 
                    pstmt.setBinaryStream(6, (InputStream)fis5, (int)(file5.length())); 
                    pstmt.setBinaryStream(13, (InputStream)fis6, (int)(file6.length())); 
                    
                    pstmt.setString(7, file.getName());
                    pstmt.setString(8, file1.getName());
                    pstmt.setString(9, file2.getName());
                    pstmt.setString(10, file3.getName());
                    pstmt.setString(11, file4.getName());
                    pstmt.setString(12, file5.getName());
                    //pstmt.setString(13, file6.getName());
                    
                    
                     int i = pstmt.executeUpdate();                     
                     if(i!=0){
                         JOptionPane.showMessageDialog(null,"Image cropped","success",1);
                           jTextField1.setText("");
                           jTextField2.setText("");
                           jTextField3.setText("");
                           jTextField4.setText("");
                           jTextField5.setText("");
                           jTextField6.setText("");
                           jTextField7.setText("");
                     }                         
              }  catch (ClassNotFoundException ex) 
                   {
                    Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                   }
                 catch (SQLException ex) 
                  {
                   Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                  }
                 catch (FileNotFoundException ex) {
                Logger.getLogger(crop_image.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField7.setText(file.toString());
       }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       new Operator().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new crop_image().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
