package NewPack;



/*
 * eyewitness.java
 *

 */

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class eyewitness extends javax.swing.JFrame {

    /** Creates new form eyewitness */
    public eyewitness() {
        initComponents();
       
        try {             
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
             Statement st = conn.createStatement();
             String qqq = "select * from crop ";
             ResultSet rs = st.executeQuery(qqq);
              while(rs.next()){                   
                   String category = rs.getString("h");                 
                   jComboBox1.addItem(category);
                   String category1 = rs.getString("f");                 
                   jComboBox2.addItem(category1);
                   String category2 = rs.getString("e");                 
                   jComboBox3.addItem(category2);
                   String category3 = rs.getString("n");                 
                   jComboBox4.addItem(category3);
                   String category4 = rs.getString("m");                 
                   jComboBox5.addItem(category4);
                   String category5 = rs.getString("c");                 
                   jComboBox6.addItem(category5);
                   
              }
        
         }catch (ClassNotFoundException ex) {
          Logger.getLogger(eyewitness.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
          Logger.getLogger(eyewitness.class.getName()).log(Level.SEVERE, null, ex);
         }
        
       
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(270, 120, 150, 150));
        setMinimumSize(new java.awt.Dimension(850, 465));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Hair");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 40, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("ForeHead");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 70, 59, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Eyes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 70, 28, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Eyewitness");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 10, 190, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("Chin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 70, 30, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 100, 67, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(110, 100, 86, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(210, 100, 69, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(300, 100, 89, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(410, 100, 85, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(510, 100, 78, 20);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 218, 259, 30);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 255, 259, 20);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 319, 259, 20);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 283, 259, 30);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 374, 259, 20);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 346, 259, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Click To See");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 100, 120, 25);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(470, 210, 259, 209);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Full Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(730, 100, 111, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("SignOut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 10, 100, 25);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 102));
        jLabel15.setText("Nose");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 70, 26, 14);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 255, 102));
        jLabel14.setText("Hair");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 70, 40, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 102));
        jLabel13.setText("Lips");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 70, 26, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPack/resources/eyewitness.jpg"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(-20, 0, 880, 460);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
      //  JOptionPane.showMessageDialog(null,"selected");
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(null,"selected");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {             
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
             Statement st = conn.createStatement();           
             String qqq = "select * from crop";
             System.out.println("Query   >>>"+qqq);
             ResultSet rs = st.executeQuery(qqq);
              while(rs.next()){
                  String ww = rs.getString("h");
                  if(ww.equals(jComboBox1.getSelectedItem().toString())){
                      
                      Blob blob = rs.getBlob("hair");
                    byte a[]= blob.getBytes(1, (int) blob.length());
                    ImageIcon imgf=new ImageIcon(a);
                    int width=imgf.getIconWidth();  
                    int height=imgf.getIconHeight();
                     jLabel7.setIcon(imgf);
                     }
                  String ww1 = rs.getString("f");
                  if(ww1.equals(jComboBox2.getSelectedItem().toString())){
                      
                      Blob blob1 = rs.getBlob("forehd");
                    byte a1[]= blob1.getBytes(1, (int) blob1.length());
                    ImageIcon imgf1=new ImageIcon(a1); 
                     jLabel8.setIcon(imgf1);
                     }
                    String ww2 = rs.getString("e");
                  if(ww2.equals(jComboBox3.getSelectedItem().toString())){
                      
                      Blob blob2 = rs.getBlob("eye");
                    byte a2[]= blob2.getBytes(1, (int) blob2.length());
                    ImageIcon imgf2=new ImageIcon(a2); 
                     jLabel10.setIcon(imgf2);
                     }
                   String ww3 = rs.getString("n");
                  if(ww3.equals(jComboBox4.getSelectedItem().toString())){
                      
                      Blob blob3 = rs.getBlob("nose");
                    byte a3[]= blob3.getBytes(1, (int) blob3.length());
                    ImageIcon imgf3=new ImageIcon(a3); 
                     jLabel9.setIcon(imgf3);
                     }
                   String ww4 = rs.getString("m");
                  if(ww4.equals(jComboBox5.getSelectedItem().toString())){
                      
                      Blob blob4 = rs.getBlob("mouth");
                    byte a4[]= blob4.getBytes(1, (int) blob4.length());
                    ImageIcon imgf4=new ImageIcon(a4); 
                     jLabel12.setIcon(imgf4);
                     }
                   String ww5 = rs.getString("c");
                  if(ww5.equals(jComboBox6.getSelectedItem().toString())){
                      
                      Blob blob5 = rs.getBlob("chin");
                    byte a5[]= blob5.getBytes(1, (int) blob5.length());
                    ImageIcon imgf5=new ImageIcon(a5); 
                     jLabel11.setIcon(imgf5);
                     }
                  
                     
      }
   }    catch (ClassNotFoundException ex) {
          Logger.getLogger(eyewitness.class.getName()).log(Level.SEVERE, null, ex);
             }
        catch (SQLException ex) {
          Logger.getLogger(eyewitness.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {   
                 
                 
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
                     Statement st = conn.createStatement();           
                     String Query = "select * from crop where  h = '"+jComboBox1.getSelectedItem().toString()+"' "+" AND f = '"+jComboBox2.getSelectedItem().toString()+"' "+" AND e = '"+jComboBox3.getSelectedItem().toString()+"' "+" AND n = '"+jComboBox4.getSelectedItem().toString()+"' "+" AND m = '"+jComboBox5.getSelectedItem().toString()+"' "+" AND c = '"+jComboBox6.getSelectedItem().toString()+"'    ";                      
                     ResultSet rs = st.executeQuery(Query);
                     if(rs.next()){
                           Blob blob6 = rs.getBlob("fullimage");
                           byte a6[]= blob6.getBytes(1, (int) blob6.length());
                           ImageIcon imgf6=new ImageIcon(a6); 
                           jLabel18.setText("");
                           jLabel18.setIcon(imgf6);  
                           JOptionPane.showMessageDialog(null,"FACE DETECTED","Success",1);
                     }
                     else{
                               jLabel18.setIcon(null);
                               jLabel18.setText("NO IMAGES FOUND");
                               jLabel18.setForeground(Color.green);
                     }
                        
                        /* String q1 = rs.getString("h");
                         String q2 = rs.getString("f");                         
                         String q3 = rs.getString("e");
                         String q4 = rs.getString("n");
                         String q5 = rs.getString("m");
                         String q6 = rs.getString("c");
                         if((q1.equals(jComboBox1.getSelectedItem().toString())) && (q2.equals(jComboBox2.getSelectedItem().toString())) && (q3.equals(jComboBox3.getSelectedItem().toString())) && (q4.equals(jComboBox4.getSelectedItem().toString())) && (q5.equals(jComboBox5.getSelectedItem().toString())) && (q6.equals(jComboBox6.getSelectedItem().toString()))){
                             System.out.println("Found");
                           Blob blob6 = rs.getBlob("fullimage");
                           byte a6[]= blob6.getBytes(1, (int) blob6.length());
                           ImageIcon imgf6=new ImageIcon(a6); 
                           jLabel18.setText("");
                           jLabel18.setIcon(imgf6);                          
                         }
                         else{
                             System.out.println("Not Found");
                              jLabel18.setIcon(null);
                              jLabel18.setText("NO IMAGES FOUND");
                         } */
                         
                         
                         
                     
                                        
                                              
              }  catch (ClassNotFoundException ex) 
                   {
                    Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                   }
                 catch (SQLException ex) 
                  {
                   Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                  }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new eyewitness().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
