package NewPack;


import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;



/*
 * New_Criminal.java
 *

 */

public class New_Criminal extends javax.swing.JFrame {

    /** Creates new form New_Criminal */
    public New_Criminal() {
        initComponents();
         jTextField1.setText("Default");
         jTextField1.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(360, 70, 150, 150));
        setMinimumSize(new java.awt.Dimension(600, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Criminal ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(103, 88, 80, 14);

        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(103, 126, 70, 14);

        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(103, 164, 80, 14);

        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Alias Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(103, 205, 70, 14);

        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("D.O.B");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(103, 240, 70, 14);

        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("Age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(103, 278, 60, 14);

        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(103, 316, 70, 14);

        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("City");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(103, 354, 60, 14);

        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("State");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(103, 392, 60, 14);

        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Arrest Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(103, 430, 80, 14);

        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("Crime Involved");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(103, 468, 90, 14);

        jLabel12.setForeground(new java.awt.Color(51, 255, 51));
        jLabel12.setText("Image");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(103, 507, 50, 14);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 51));
        jLabel13.setText("NEW DETAIL");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 10, 250, 42);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(205, 85, 170, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(205, 123, 170, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(205, 161, 170, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(205, 199, 170, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(205, 237, 170, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(205, 275, 170, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(205, 313, 170, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(205, 351, 170, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(205, 389, 170, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(205, 427, 170, 20);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(205, 465, 170, 20);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(205, 504, 170, 20);

        jButton1.setText("Browse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(411, 503, 80, 23);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(195, 553, 60, 23);

        jButton3.setText("Reset");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(274, 553, 70, 23);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 0, 70, 25);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPack/resources/new Crriminal.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-10, 0, 730, 610);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
          JFileChooser Chooser = new JFileChooser();
        Chooser.setMultiSelectionEnabled(true);
        Chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = Chooser.showDialog(this,"Open");
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = Chooser.getSelectedFile();
            jTextField12.setText(file.toString());
       }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
      
       String t2 =  jTextField2.getText();
       String t3 =  jTextField3.getText();
       String t4 =  jTextField4.getText();
       String t5 =  jTextField5.getText();
       String t6 =  jTextField6.getText();
       String t7 =  jTextField7.getText();
       String t8 =  jTextField8.getText();
       String t9 =  jTextField9.getText();
       String t10 = jTextField10.getText();
       String t11 = jTextField11.getText();
       String t12 = jTextField12.getText();

     
        try {   
                 String fileName = jTextField12.getText();
                 File file = new File(fileName);
                 FileInputStream fis = new FileInputStream(file);
                 
                      Class.forName("com.mysql.jdbc.Driver");
                      Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
                      PreparedStatement pstmt = conn.prepareStatement("insert into new_details (fname,lname,alias,dob,age,gender,city,state,ardate,crime,image)values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                      pstmt.setString(1, t2);
                      pstmt.setString(2, t3);
                      pstmt.setString(3, t4);
                      pstmt.setString(4, t5);
                      pstmt.setString(5, t6);
                      pstmt.setString(6, t7);
                      pstmt.setString(7, t8);
                      pstmt.setString(8, t9);
                      pstmt.setString(9, t10);
                      pstmt.setString(10, t11);
                      
                      pstmt.setBinaryStream(11, (InputStream)fis, (int)(file.length()));              
                     int i = pstmt.executeUpdate();                     
                     if(i!=0){
                         JOptionPane.showMessageDialog(null,"Criminal Details added","success",1);
                          jTextField2.setText("");
                          jTextField3.setText("");
                          jTextField4.setText("");
                          jTextField5.setText("");
                          jTextField6.setText("");
                          jTextField7.setText("");
                          jTextField8.setText("");
                          jTextField9.setText("");
                          jTextField10.setText("");
                          jTextField11.setText("");
                          jTextField12.setText("");
                     }                         
              }  catch (ClassNotFoundException ex) 
                   {
                    Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                   }
                 catch (SQLException ex) 
                  {
                   Logger.getLogger(New_Criminal.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  catch(IOException e){} 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
               new Operator().setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new New_Criminal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
