package NewPack;



/*
 * signup_details.java
 *

 */
/**
 *

 */
import java.sql.*;
import javax.swing.*;
public class signup_detail extends javax.swing.JFrame {

    /** Creates new form signup_details */
    public signup_detail() {
        initComponents();
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jComboBox1.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(320, 100, 100, 100));
        setMinimumSize(new java.awt.Dimension(600, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText(" If you are EYEWITNESS , to find existing criminal faces   ?   ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 381, 17);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("CLICK HERE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 60, 130, 25);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 80, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("If you are new OPERATOR ,to manipulate criminal details  ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 376, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("OR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 90, 21, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "OPERATOR", "EYEWITNESS" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(330, 280, 153, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(330, 180, 153, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(330, 230, 153, 20);

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton12.setText("Submit");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(240, 350, 80, 23);

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton13.setText("Cancel");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(360, 350, 80, 23);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 255, 51));
        jLabel18.setText("Username");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(190, 180, 100, 17);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 255, 51));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(190, 230, 100, 17);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 255, 51));
        jLabel19.setText("Mode");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(190, 280, 33, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPack/resources/signup.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 690, 470);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jTextField8.setVisible(true);
        jTextField9.setVisible(true);
        jComboBox1.setVisible(true);
        jButton12.setVisible(true);
        jButton13.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
       new Main_Window().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        jTextField8.setText("");
        jTextField9.setText("");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if("".equals(jTextField8.getText()) || "".equals(jTextField9.getText()) ) {
            JOptionPane.showMessageDialog(null,"Enter Username and Password");
        } else{
            try {
                String f = jTextField8.getText();
                String f1 = jTextField9.getText();
                String f2 = jComboBox1.getSelectedItem().toString();
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crime", "root", "root");
                Statement st = conn.createStatement();
                String Q = "insert into login values('"+f+"','"+f1+"','"+f2+"') ";
                int i = st.executeUpdate(Q);
                if(i!=0){
                    JOptionPane.showMessageDialog(null,"signup success","SUCCESS",1);
                    jTextField8.setText("");
                    jTextField9.setText("");
                }
            }catch (ClassNotFoundException ex) {
                System.out.print(ex);
            } catch (SQLException ex1) {
                System.out.print(ex1);
            }
        }
}//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jButton12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new signup_detail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
